# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'
minimum_ios_version = '15.0'

source "https://github.com/CocoaPods/Specs"
source 'https://github.com/aliyun/aliyun-specs.git'

## workspace文件名
workspace 'ddlNew.xcworkspace'

target 'ddlNew' do
  # Comment the next line if you don't want to use dynamic frameworks
  project './ddlNew.xcodeproj'
  use_frameworks!

  # Pods for ddlNew
  
  #aliyun云解析DNS
  pod 'AlicloudPDNS', '2.1.9'
  pod 'WoodPeckeriOS', :configurations => ['Debug']


end

target 'CandyTalkPro' do
  project './NoaChatSDKCore/CandyTalkPro.xcodeproj'
  use_frameworks!

  pod "AFNetworking", '4.0.1'
  pod 'MJExtension', '3.4.0'
  pod 'SocketRocket', '0.6.0'
  pod 'MMKV', '1.2.16'
  pod 'NullSafe', '2.0'
  pod 'Protobuf', '3.21.5'
  #新的架构实现SDK
  pod 'CocoaAsyncSocket', '7.6.5'
  pod 'SAMKeychain', '1.5.3'

  #音视频要求iOS13最低(SwiftUI)
  pod 'LiveKitClient', '1.0.8'

  #即构音视频
  pod 'ZegoExpressEngine', '3.5.0'

  # 错误监控
#  pod 'Sentry', '8.58.3'


  # RAC
  pod 'ReactiveObjC', :inhibit_warnings => true

  # 网络监听
  pod 'NetworkStatus', :path => './NetWorkStatus/NetWorkStatus.podspec'

end



post_install do |installer|
  # Xcode 26 SDK no longer exposes this private IPv6 header directly. These
  # sources already import <netinet/in.h>, which provides the required IPv6
  # declarations. Apply the patch after every `pod install`, because files
  # under Pods are regenerated by CocoaPods.
  files_with_obsolete_ipv6_import = [
    'Reachability/Reachability.m',
    'AFNetworking/AFNetworking/AFNetworkReachabilityManager.m',
    'AFNetworking/AFNetworking/AFHTTPSessionManager.m',
    'QCloudCore/QCloudCore/Classes/Base/QCLOUDRestNet/reachability/QCloudReachability.m',
    'QCloudTrack/QCloudTrack/Classes/Default/Utils/QCloudTrackNetworkUtils.m'
  ]

  files_with_obsolete_ipv6_import.each do |relative_path|
    source_file = File.join(installer.sandbox.root.to_s, relative_path)
    next unless File.exist?(source_file)

    source = File.read(source_file)
    patched_source = source.gsub(/^\s*#import\s+<netinet6\/in6\.h>\s*\r?\n/, '')

    if patched_source != source
      original_mode = File.stat(source_file).mode
      File.chmod(original_mode | 0200, source_file)
      begin
        File.write(source_file, patched_source)
      ensure
        File.chmod(original_mode, source_file)
      end
      puts "Removed <netinet6/in6.h> import from #{relative_path} for Xcode 26 compatibility"
    end
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Xcode 27 最低支持 iOS 15；保留 Pod 自身更高的最低版本要求。
      deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] || minimum_ios_version
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = [Gem::Version.new(deployment_target), Gem::Version.new(minimum_ios_version)].max.to_s
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      # 部分 Pod（如 CocoaLumberjack）会声明 Swift 6.x，旧版 Xcode 只支持到 5.0
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGN_IDENTITY'] = ''
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
