// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Nav.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct NavMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///消息类型
  var dataType: NavMessage.DataType = .navAuth

  ///oneof表示多个当中有一个被赋值
  var dataBody: NavMessage.OneOf_DataBody? = nil

  ///下面类型同一时刻只能出现一个
  var auth: Auth {
    get {
      if case .auth(let v)? = dataBody {return v}
      return Auth()
    }
    set {dataBody = .auth(newValue)}
  }

  var authAck: AuthAck {
    get {
      if case .authAck(let v)? = dataBody {return v}
      return AuthAck()
    }
    set {dataBody = .authAck(newValue)}
  }

  var imServerListRequest: IMServerListRequest {
    get {
      if case .imServerListRequest(let v)? = dataBody {return v}
      return IMServerListRequest()
    }
    set {dataBody = .imServerListRequest(newValue)}
  }

  var imServerListResponse: IMServerListResponse {
    get {
      if case .imServerListResponse(let v)? = dataBody {return v}
      return IMServerListResponse()
    }
    set {dataBody = .imServerListResponse(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  ///oneof表示多个当中有一个被赋值
  nonisolated enum OneOf_DataBody: Equatable, Sendable {
    ///下面类型同一时刻只能出现一个
    case auth(Auth)
    case authAck(AuthAck)
    case imServerListRequest(IMServerListRequest)
    case imServerListResponse(IMServerListResponse)

  }

  nonisolated enum DataType: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int

    ///认证消息
    case navAuth // = 0

    ///认证回执消息
    case navAuthAck // = 1

    ///IM服务器列表请求
    case imServerListReq // = 2

    ///IM服务器列表响应
    case imServerListResp // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .navAuth
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .navAuth
      case 1: self = .navAuthAck
      case 2: self = .imServerListReq
      case 3: self = .imServerListResp
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .navAuth: return 0
      case .navAuthAck: return 1
      case .imServerListReq: return 2
      case .imServerListResp: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [NavMessage.DataType] = [
      .navAuth,
      .navAuthAck,
      .imServerListReq,
      .imServerListResp,
    ]

  }

  init() {}
}

nonisolated struct Auth: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 企业号
  var appkey: String = String()

  /// 13位UTC时间戳
  var timestamp: Int64 = 0

  /// 设备sn码
  var sn: String = String()

  /// 随机字符串
  var nonce: String = String()

  /// app类型 0:公共打包 1:独立打包
  var appType: Int32 = 0

  /// appkey+timestamp+sn+nonce+appType AES加密
  var sign: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct AuthAck: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 状态码 200 成功 401 企业号不存在 402 解密失败 403 IP被封禁 404 设备被封禁 501 服务端异常
  var code: Int64 = 0

  /// 消息内容
  var message: String = String()

  /// 导航数据
  var data: NavData {
    get {_data ?? NavData()}
    set {_data = newValue}
  }
  /// Returns true if `data` has been explicitly set.
  var hasData: Bool {self._data != nil}
  /// Clears the value of `data`. Subsequent reads from it will return its default value.
  mutating func clearData() {self._data = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _data: NavData? = nil
}

/// 导航数据
nonisolated struct NavData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 导航加密字符串
  var navEncryptStr: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// IM服务器列表请求协议（客户端 → 导航服务）
nonisolated struct IMServerListRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 【必填】企业号
  var appID: String = String()

  /// app类型 0:公共打包 1:独立打包
  var appType: IMServerListRequest.DataType = .common

  /// 【必填】客户端版本
  var clientVersion: String = String()

  /// 【必填】地区标识 (CN/US/EU/AP)
  var region: String = String()

  /// 【必填】设备类型 (ios/android/pc/web)
  var deviceType: String = String()

  /// 【必填】请求时间戳
  var timestamp: Int64 = 0

  /// 【必填】请求签名
  var signature: String = String()

  /// 【非必填】客户端IP地址
  var clientIp: String = String()

  /// 【非必填】SDK版本
  var sdkVersion: String = String()

  /// 【必填】随机字符串，防重放攻击
  var nonce: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum DataType: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int

    /// 公共打包
    case common // = 0

    /// 独立打包
    case independent // = 1
    case UNRECOGNIZED(Int)

    init() {
      self = .common
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .common
      case 1: self = .independent
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .common: return 0
      case .independent: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [IMServerListRequest.DataType] = [
      .common,
      .independent,
    ]

  }

  init() {}
}

/// IM服务器列表响应协议（导航服务 → 客户端）
nonisolated struct IMServerListResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 【必填】状态码（使用6位错误码）
  var statusCode: Int32 = 0

  /// 【必填】响应消息
  var message: String = String()

  /// 【必填】加密的响应体数据
  var responseBody: Data = Data()

  /// 【必填】服务器时间戳
  var serverTimestamp: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// IM服务器列表响应体（加密传输）
nonisolated struct IMServerListResponseBody: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 【必填】IM服务器列表
  var imEndpoints: [IMServerEndpoint] = []

  /// 【非必填】元数据信息
  var meta: NavigationMeta {
    get {_meta ?? NavigationMeta()}
    set {_meta = newValue}
  }
  /// Returns true if `meta` has been explicitly set.
  var hasMeta: Bool {self._meta != nil}
  /// Clears the value of `meta`. Subsequent reads from it will return its default value.
  mutating func clearMeta() {self._meta = nil}

  /// 【非必填】兜底导航地址
  var fallbackEndpoints: FallbackEndpoints {
    get {_fallbackEndpoints ?? FallbackEndpoints()}
    set {_fallbackEndpoints = newValue}
  }
  /// Returns true if `fallbackEndpoints` has been explicitly set.
  var hasFallbackEndpoints: Bool {self._fallbackEndpoints != nil}
  /// Clears the value of `fallbackEndpoints`. Subsequent reads from it will return its default value.
  mutating func clearFallbackEndpoints() {self._fallbackEndpoints = nil}

  /// 【必填】缓存有效期(秒)
  var cacheTtl: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _meta: NavigationMeta? = nil
  fileprivate var _fallbackEndpoints: FallbackEndpoints? = nil
}

/// IM服务器节点信息
nonisolated struct IMServerEndpoint: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 【必填】IP地址
  var ip: String = String()

  /// 【必填】端口号
  var port: Int32 = 0

  /// 【必填】权重(1-100)
  var weight: Int32 = 0

  /// 【非必填】所属地区
  var region: String = String()

  /// 【必填】状态(ACTIVE/INACTIVE)
  var status: String = String()

  /// 【非必填】延迟(ms)
  var latency: Int64 = 0

  /// 【必填】服务器标识
  var serverID: String = String()

  /// 【非必填】集群标识
  var clusterID: String = String()

  /// 【非必填】当前负载(0-100)
  var load: Int32 = 0

  /// 【非必填】支持的协议列表
  var protocols: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 导航元数据
nonisolated struct NavigationMeta: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 【必填】导航服务版本
  var navVersion: String = String()

  /// 【非必填】客户端配置
  var config: NavigationConfig {
    get {_config ?? NavigationConfig()}
    set {_config = newValue}
  }
  /// Returns true if `config` has been explicitly set.
  var hasConfig: Bool {self._config != nil}
  /// Clears the value of `config`. Subsequent reads from it will return its default value.
  mutating func clearConfig() {self._config = nil}

  /// 【非必填】下次更新时间
  var nextUpdateTime: Int64 = 0

  /// 【非必填】请求追踪ID
  var traceID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _config: NavigationConfig? = nil
}

/// 客户端配置
nonisolated struct NavigationConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 【非必填】连接超时(ms)，默认10000
  var connectTimeout: Int32 = 0

  /// 【非必填】读取超时(ms)，默认5000
  var readTimeout: Int32 = 0

  /// 【非必填】最大重试次数，默认3
  var maxRetryCount: Int32 = 0

  /// 【非必填】竞速超时(ms)，默认3000
  var raceTimeout: Int32 = 0

  /// 【非必填】缓存时长(秒)，默认3600
  var cacheDuration: Int32 = 0

  /// 【非必填】是否启用网络探测，默认true
  var enableNetworkDetect: Bool = false

  /// 【非必填】Sentry服务地址列表
  var sentryUrls: [String] = []

  /// 【非必填】Logan服务地址列表
  var loganUrls: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 兜底导航地址
nonisolated struct FallbackEndpoints: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 【非必填】国内导航地址
  var domestic: [String] = []

  /// 【非必填】海外导航地址
  var overseas: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

nonisolated extension NavMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "NavMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}data_type\0\u{1}auth\0\u{1}authAck\0\u{1}imServerListRequest\0\u{1}imServerListResponse\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.dataType) }()
      case 2: try {
        var v: Auth?
        var hadOneofValue = false
        if let current = self.dataBody {
          hadOneofValue = true
          if case .auth(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.dataBody = .auth(v)
        }
      }()
      case 3: try {
        var v: AuthAck?
        var hadOneofValue = false
        if let current = self.dataBody {
          hadOneofValue = true
          if case .authAck(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.dataBody = .authAck(v)
        }
      }()
      case 4: try {
        var v: IMServerListRequest?
        var hadOneofValue = false
        if let current = self.dataBody {
          hadOneofValue = true
          if case .imServerListRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.dataBody = .imServerListRequest(v)
        }
      }()
      case 5: try {
        var v: IMServerListResponse?
        var hadOneofValue = false
        if let current = self.dataBody {
          hadOneofValue = true
          if case .imServerListResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.dataBody = .imServerListResponse(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.dataType != .navAuth {
      try visitor.visitSingularEnumField(value: self.dataType, fieldNumber: 1)
    }
    switch self.dataBody {
    case .auth?: try {
      guard case .auth(let v)? = self.dataBody else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .authAck?: try {
      guard case .authAck(let v)? = self.dataBody else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .imServerListRequest?: try {
      guard case .imServerListRequest(let v)? = self.dataBody else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .imServerListResponse?: try {
      guard case .imServerListResponse(let v)? = self.dataBody else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: NavMessage, rhs: NavMessage) -> Bool {
    if lhs.dataType != rhs.dataType {return false}
    if lhs.dataBody != rhs.dataBody {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension NavMessage.DataType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0navAuth\0\u{1}navAuthAck\0\u{1}imServerListReq\0\u{1}imServerListResp\0")
}

nonisolated extension Auth: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Auth"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}appkey\0\u{1}timestamp\0\u{1}sn\0\u{1}nonce\0\u{1}appType\0\u{1}sign\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.appkey) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.timestamp) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.sn) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.nonce) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.appType) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.sign) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.appkey.isEmpty {
      try visitor.visitSingularStringField(value: self.appkey, fieldNumber: 1)
    }
    if self.timestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.timestamp, fieldNumber: 2)
    }
    if !self.sn.isEmpty {
      try visitor.visitSingularStringField(value: self.sn, fieldNumber: 3)
    }
    if !self.nonce.isEmpty {
      try visitor.visitSingularStringField(value: self.nonce, fieldNumber: 4)
    }
    if self.appType != 0 {
      try visitor.visitSingularInt32Field(value: self.appType, fieldNumber: 5)
    }
    if !self.sign.isEmpty {
      try visitor.visitSingularStringField(value: self.sign, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Auth, rhs: Auth) -> Bool {
    if lhs.appkey != rhs.appkey {return false}
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.sn != rhs.sn {return false}
    if lhs.nonce != rhs.nonce {return false}
    if lhs.appType != rhs.appType {return false}
    if lhs.sign != rhs.sign {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension AuthAck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "AuthAck"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}message\0\u{1}data\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._data) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.code != 0 {
      try visitor.visitSingularInt64Field(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try { if let v = self._data {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: AuthAck, rhs: AuthAck) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs._data != rhs._data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension NavData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "NavData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}navEncryptStr\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.navEncryptStr) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.navEncryptStr.isEmpty {
      try visitor.visitSingularStringField(value: self.navEncryptStr, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: NavData, rhs: NavData) -> Bool {
    if lhs.navEncryptStr != rhs.navEncryptStr {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension IMServerListRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "IMServerListRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}app_id\0\u{1}appType\0\u{3}client_version\0\u{1}region\0\u{3}device_type\0\u{1}timestamp\0\u{1}signature\0\u{3}client_ip\0\u{3}sdk_version\0\u{1}nonce\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.appID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.appType) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.clientVersion) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.region) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.deviceType) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.timestamp) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.signature) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.clientIp) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.sdkVersion) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.nonce) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.appID.isEmpty {
      try visitor.visitSingularStringField(value: self.appID, fieldNumber: 1)
    }
    if self.appType != .common {
      try visitor.visitSingularEnumField(value: self.appType, fieldNumber: 2)
    }
    if !self.clientVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.clientVersion, fieldNumber: 3)
    }
    if !self.region.isEmpty {
      try visitor.visitSingularStringField(value: self.region, fieldNumber: 4)
    }
    if !self.deviceType.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceType, fieldNumber: 5)
    }
    if self.timestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.timestamp, fieldNumber: 6)
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularStringField(value: self.signature, fieldNumber: 7)
    }
    if !self.clientIp.isEmpty {
      try visitor.visitSingularStringField(value: self.clientIp, fieldNumber: 8)
    }
    if !self.sdkVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.sdkVersion, fieldNumber: 9)
    }
    if !self.nonce.isEmpty {
      try visitor.visitSingularStringField(value: self.nonce, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: IMServerListRequest, rhs: IMServerListRequest) -> Bool {
    if lhs.appID != rhs.appID {return false}
    if lhs.appType != rhs.appType {return false}
    if lhs.clientVersion != rhs.clientVersion {return false}
    if lhs.region != rhs.region {return false}
    if lhs.deviceType != rhs.deviceType {return false}
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.clientIp != rhs.clientIp {return false}
    if lhs.sdkVersion != rhs.sdkVersion {return false}
    if lhs.nonce != rhs.nonce {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension IMServerListRequest.DataType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0COMMON\0\u{1}INDEPENDENT\0")
}

nonisolated extension IMServerListResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "IMServerListResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}status_code\0\u{1}message\0\u{3}response_body\0\u{3}server_timestamp\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.statusCode) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.responseBody) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.serverTimestamp) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.statusCode != 0 {
      try visitor.visitSingularInt32Field(value: self.statusCode, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.responseBody.isEmpty {
      try visitor.visitSingularBytesField(value: self.responseBody, fieldNumber: 3)
    }
    if self.serverTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.serverTimestamp, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: IMServerListResponse, rhs: IMServerListResponse) -> Bool {
    if lhs.statusCode != rhs.statusCode {return false}
    if lhs.message != rhs.message {return false}
    if lhs.responseBody != rhs.responseBody {return false}
    if lhs.serverTimestamp != rhs.serverTimestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension IMServerListResponseBody: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "IMServerListResponseBody"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}im_endpoints\0\u{1}meta\0\u{3}fallback_endpoints\0\u{3}cache_ttl\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.imEndpoints) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._meta) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._fallbackEndpoints) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.cacheTtl) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.imEndpoints.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.imEndpoints, fieldNumber: 1)
    }
    try { if let v = self._meta {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._fallbackEndpoints {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.cacheTtl != 0 {
      try visitor.visitSingularInt64Field(value: self.cacheTtl, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: IMServerListResponseBody, rhs: IMServerListResponseBody) -> Bool {
    if lhs.imEndpoints != rhs.imEndpoints {return false}
    if lhs._meta != rhs._meta {return false}
    if lhs._fallbackEndpoints != rhs._fallbackEndpoints {return false}
    if lhs.cacheTtl != rhs.cacheTtl {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension IMServerEndpoint: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "IMServerEndpoint"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ip\0\u{1}port\0\u{1}weight\0\u{1}region\0\u{1}status\0\u{1}latency\0\u{3}server_id\0\u{3}cluster_id\0\u{1}load\0\u{1}protocols\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.ip) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.port) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.weight) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.region) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.status) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.latency) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.serverID) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.clusterID) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self.load) }()
      case 10: try { try decoder.decodeRepeatedStringField(value: &self.protocols) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.ip.isEmpty {
      try visitor.visitSingularStringField(value: self.ip, fieldNumber: 1)
    }
    if self.port != 0 {
      try visitor.visitSingularInt32Field(value: self.port, fieldNumber: 2)
    }
    if self.weight != 0 {
      try visitor.visitSingularInt32Field(value: self.weight, fieldNumber: 3)
    }
    if !self.region.isEmpty {
      try visitor.visitSingularStringField(value: self.region, fieldNumber: 4)
    }
    if !self.status.isEmpty {
      try visitor.visitSingularStringField(value: self.status, fieldNumber: 5)
    }
    if self.latency != 0 {
      try visitor.visitSingularInt64Field(value: self.latency, fieldNumber: 6)
    }
    if !self.serverID.isEmpty {
      try visitor.visitSingularStringField(value: self.serverID, fieldNumber: 7)
    }
    if !self.clusterID.isEmpty {
      try visitor.visitSingularStringField(value: self.clusterID, fieldNumber: 8)
    }
    if self.load != 0 {
      try visitor.visitSingularInt32Field(value: self.load, fieldNumber: 9)
    }
    if !self.protocols.isEmpty {
      try visitor.visitRepeatedStringField(value: self.protocols, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: IMServerEndpoint, rhs: IMServerEndpoint) -> Bool {
    if lhs.ip != rhs.ip {return false}
    if lhs.port != rhs.port {return false}
    if lhs.weight != rhs.weight {return false}
    if lhs.region != rhs.region {return false}
    if lhs.status != rhs.status {return false}
    if lhs.latency != rhs.latency {return false}
    if lhs.serverID != rhs.serverID {return false}
    if lhs.clusterID != rhs.clusterID {return false}
    if lhs.load != rhs.load {return false}
    if lhs.protocols != rhs.protocols {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension NavigationMeta: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "NavigationMeta"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}nav_version\0\u{1}config\0\u{3}next_update_time\0\u{3}trace_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.navVersion) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._config) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.nextUpdateTime) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.traceID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.navVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.navVersion, fieldNumber: 1)
    }
    try { if let v = self._config {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.nextUpdateTime != 0 {
      try visitor.visitSingularInt64Field(value: self.nextUpdateTime, fieldNumber: 3)
    }
    if !self.traceID.isEmpty {
      try visitor.visitSingularStringField(value: self.traceID, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: NavigationMeta, rhs: NavigationMeta) -> Bool {
    if lhs.navVersion != rhs.navVersion {return false}
    if lhs._config != rhs._config {return false}
    if lhs.nextUpdateTime != rhs.nextUpdateTime {return false}
    if lhs.traceID != rhs.traceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension NavigationConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "NavigationConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}connect_timeout\0\u{3}read_timeout\0\u{3}max_retry_count\0\u{3}race_timeout\0\u{3}cache_duration\0\u{3}enable_network_detect\0\u{3}sentry_urls\0\u{3}logan_urls\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.connectTimeout) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.readTimeout) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.maxRetryCount) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.raceTimeout) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.cacheDuration) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.enableNetworkDetect) }()
      case 7: try { try decoder.decodeRepeatedStringField(value: &self.sentryUrls) }()
      case 8: try { try decoder.decodeRepeatedStringField(value: &self.loganUrls) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.connectTimeout != 0 {
      try visitor.visitSingularInt32Field(value: self.connectTimeout, fieldNumber: 1)
    }
    if self.readTimeout != 0 {
      try visitor.visitSingularInt32Field(value: self.readTimeout, fieldNumber: 2)
    }
    if self.maxRetryCount != 0 {
      try visitor.visitSingularInt32Field(value: self.maxRetryCount, fieldNumber: 3)
    }
    if self.raceTimeout != 0 {
      try visitor.visitSingularInt32Field(value: self.raceTimeout, fieldNumber: 4)
    }
    if self.cacheDuration != 0 {
      try visitor.visitSingularInt32Field(value: self.cacheDuration, fieldNumber: 5)
    }
    if self.enableNetworkDetect != false {
      try visitor.visitSingularBoolField(value: self.enableNetworkDetect, fieldNumber: 6)
    }
    if !self.sentryUrls.isEmpty {
      try visitor.visitRepeatedStringField(value: self.sentryUrls, fieldNumber: 7)
    }
    if !self.loganUrls.isEmpty {
      try visitor.visitRepeatedStringField(value: self.loganUrls, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: NavigationConfig, rhs: NavigationConfig) -> Bool {
    if lhs.connectTimeout != rhs.connectTimeout {return false}
    if lhs.readTimeout != rhs.readTimeout {return false}
    if lhs.maxRetryCount != rhs.maxRetryCount {return false}
    if lhs.raceTimeout != rhs.raceTimeout {return false}
    if lhs.cacheDuration != rhs.cacheDuration {return false}
    if lhs.enableNetworkDetect != rhs.enableNetworkDetect {return false}
    if lhs.sentryUrls != rhs.sentryUrls {return false}
    if lhs.loganUrls != rhs.loganUrls {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension FallbackEndpoints: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "FallbackEndpoints"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}domestic\0\u{1}overseas\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.domestic) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.overseas) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.domestic.isEmpty {
      try visitor.visitRepeatedStringField(value: self.domestic, fieldNumber: 1)
    }
    if !self.overseas.isEmpty {
      try visitor.visitRepeatedStringField(value: self.overseas, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FallbackEndpoints, rhs: FallbackEndpoints) -> Bool {
    if lhs.domestic != rhs.domestic {return false}
    if lhs.overseas != rhs.overseas {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
